name: Frontend CI

on:
  push:
    branches:
      - master  # Of een andere branch waar je op wilt luisteren (bijv. 'dev')
  pull_request:
    branches:
      - master  # Of een andere branch waar je op wilt luisteren voor PR's

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Stap 1: Haal de code op uit je repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Stap 2: Setup Node.js omgeving
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Of de versie die je gebruikt

      # Stap 3: Installeer de dependencies
      - name: Install dependencies
        run: npm install

      # Stap 4: Start vue app om de testen uit te voeren
      - name: Start the application
        run: npm run dev & # Start de app in de achtergrond

      # Stap 5: Wacht tot vue app draait
      - name: Wait for the application to be ready
        run: npx wait-on http://localhost:5173 # Wacht tot de app draait

      # Stap 6: Run Cypress End-to-End tests (zorg dat je tests hebt ingesteld)
      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          start: npm run serve  # Start je app in de testomgeving
          wait-on: 'http://localhost:5173'  # Of de URL waarop je front-end draait
          wait-on-timeout: 15  # Wacht maximaal 60 seconden totdat de server draait
          config-file: 'cypress.config.js'
