name: Frontend CI

on:
  push:
    branches:
      - master  # Of een andere branch waar je op wilt luisteren (bijv. 'dev')
  pull_request:
    branches:
      - master  # Of een andere branch waar je op wilt luisteren voor PR's

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Stap 1: Haal de code op uit je repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Stap 2: Setup Node.js omgeving
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Of de versie die je gebruikt

      # Stap 3: Installeer de dependencies
      - name: Install dependencies
        run: npm install

      # Installer docker compose
      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2

      # Start back-end
      - name: Build and run Docker Compose
        run: docker compose up &

      # Wacht totdaty backend draait
      - name: Wait for the backend
        run: npx wait-on http://localhost:9001

      # Stap 6: Run Cypress End-to-End tests (zorg dat je tests hebt ingesteld)
      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          start: npm run serve  # Start je app in de testomgeving
          wait-on: 'http://localhost:5173'  # Of de URL waarop je front-end draait
          wait-on-timeout: 15  # Wacht maximaal 60 seconden totdat de server draait
          config-file: 'cypress.config.js'

      # Stop back-end op einde
      - name: Stop Docker Compose
        run: docker compose down